apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild: 
    projectId: ticketing-dev-422012
  artifacts:
    - image: us.gcr.io/ticketing-dev-422012/auth
    # - image: danieldev1/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .